config/routes.rb
Rails.application.routes.draw do
# get 'recibir/sms'

  get  'archivos/cargar'
  post 'archivos/cargar'
  post 'archivos/borrar'
# devise_for :users
  devise_for :users, controllers: { invitations: "invitations" }
  authenticated :user do
    root to: "mensajes#new", as: "entrada"
  end
  unauthenticated :user do
    root 'pagina#index'
  end
  resources :recargas
  resources :contactos
  resources :grupos
  resources :users, except: [:new, :create]
  resources :mensajes
  resources :directos, except: [:index, :show, :edit, :update, :destroy]

  post  '/mensajes/:id'          => 'mensajes#grupo',      as: 'mgrupo'
  post  '/enviar/:id'            => 'mensajes#enviar',     as: 'enviar'
  get   '/alcance/:id'           => 'mensajes#alcance',    as: 'alcance'
  match '/invitar/'              => 'users#invitar',       via: [:get, :post]
  get   '/usuarios/'             => 'recargas#usuarios'
  get   '/recargar/:id'          => 'recargas#recargar',   as: 'recargar'
  get   '/aplicar/:id'           => 'recargas#aplicar',    as: 'aplicar'
  get   '/recibir/'              => 'recibir#sms',         as: 'recibir'
  get   '/usuario/:id'           => 'recargas#usuario',    as: 'usuario'
  get   '/usar_sms/'             => 'pagina#usar_sms'
  get   '/terminos_condiciones/' => 'pagina#terminos_condiciones'
  get   '/diccionario/'          => 'entrada#diccionario' 
  get   '/premisas/'             => 'entrada#premisas' 
  get   '/horario_sugerido/'     => 'entrada#horario_sugerido' 
  get   '/horario_grafica/'      => 'entrada#horario_grafica' 
  get   '/horario_grafica100/'   => 'entrada#horario_grafica100' 
end

app/models/recarga.rb
class Recarga < ApplicationRecord
  belongs_to :user

  validates :monto_bs,      presence: { message: "en blanco" }, 
             length: {minimum: 3, :message => "debe tener por lo menos 3 dígitos"}

end

app/controllers/recargas_controller.rb
class RecargasController < ApplicationController
  before_action :authenticate_user!
  before_action :usuario_autorizado, except: [:recargar, :new, :create]
  before_action :saldo_sms
  before_action :set_recarga, only: [:aplicar, :show, :edit, :update, :destroy]
  before_action :modo, only: [:recargar, :create]

  def usuarios
    @usuarios = User.all
    @total = @usuarios.length
  end

  def usuario
    @usuario = User.find(params[:id])
  end

  # GET /recargas
  # GET /recargas.json
  def index
    @recargas = Recarga.all.order("user_id")
  end

  # GET /recargas/1
  # GET /recargas/1.json
  def show
    @usuario = User.find(@recarga.user_id) if @recarga.user_id != 999999
  end

  def recargar
    if @modo == 'campanna'
      redirect_to new_recarga_path
    else
      redirect_to root_url, notice: 'Solo puedes pre-cargar tu propio saldo' if current_user.id.to_i != params[:id].to_i
      @usuario = User.find(params[:id])
      @recarga = Recarga.new
    end
  end

  def aplicar
    if !@recarga.f_aplicado
      if @recarga.user_id == 999999
        @usuario = User.first
        @saldo = Saldo.find_by(usuario_id: 999999) 
        nuevo_saldo = @saldo.saldo + @recarga.monto_bs
        @saldo.update_columns(saldo: nuevo_saldo)
        mensaje = 'Recarga xxx fue aplicada a la campaña'
      else
        @usuario = User.find(@recarga.user_id)
        nuevo_saldo = @usuario.saldo + @recarga.monto_bs
        @usuario.update_columns(saldo: nuevo_saldo)
        mensaje = "Recarga fue aplicada al usuario: #{@usuario.username} "
      end
      AccionCorreoMailer.aplicado(@usuario, @recarga).deliver
      @recarga.update_columns(f_aplicado: Time.now)
    else
      mensaje = 'No se aplicó la recarga al usuario, porque ya estaba aplicada'
    end
    redirect_to recargas_path, notice: mensaje
  end

  # GET /recargas/new
  def new
    @recarga = Recarga.new
  end

  # GET /recargas/1/edit
  def edit
    @usuario = User.find(@recarga.user_id) if @recarga.user_id != 999999
  end

  # POST /recargas
  # POST /recargas.json
  def create

    @recarga = Recarga.new(recarga_params)
    if @modo == 'campanna'
      @recarga.user_id = 999999
      @usuario = User.first
    else
      @usuario = User.find(@recarga.user_id)
    end
    respond_to do |format|
      if @recarga.save
        AccionCorreoMailer.recargado(@usuario, @recarga).deliver
        format.html { redirect_to @recarga, notice: 'La pre-recarga fue cargada, se envió correo' }
        format.json { render :show, status: :created, location: @recarga }
      else
        format.html { render :new }
        format.json { render json: @recarga.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recargas/1
  # PATCH/PUT /recargas/1.json
  def update
    di = @recarga.user_id
    di = 1 if di == 999999
    @usuario = User.find(di)
    respond_to do |format|
      if @recarga.update(recarga_params)
        AccionCorreoMailer.ajustado(@usuario, @recarga).deliver
        format.html { redirect_to @recarga, notice: 'Se ajustó la pre-recarga, se envió correo' }
        format.json { render :show, status: :ok, location: @recarga }
      else
        format.html { render :edit }
        format.json { render json: @recarga.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recargas/1
  # DELETE /recargas/1.json
  def destroy
    @recarga.destroy
    respond_to do |format|
      format.html { redirect_to recargas_url, notice: 'Se borró la pre-recarga' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recarga
      @recarga = Recarga.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recarga_params
      params.require(:recarga).permit(:monto_divisa, :tipo_divisa, :cambio_bs, :monto_bs, :banco_origen, :referencia_origen, :transaccion_origen, :banco_destino, :referencia_destino, :transaccion_destino, :aplicado, :user_id, :referencia, :comentarios)
    end
end

app/helpers/recargas_helper.rb
module RecargasHelper
end

app/views/recargas/_form.html.erb
<%= form_for(recarga) do |f| %>

  <% if recarga.errors.any? %>
    <%= render 'parciales/error_message', error_message: recarga.errors.full_messages.first %>
  <% end %>

  <% recarga.user_id = 999999 %>
  <% if @usuario %>
    <strong>Nombre:</strong>
    <%= @usuario.name %>
    <br>
    <strong>Usuario:</strong>
    <%= @usuario.username %>
    <br>
    <strong>Correo:</strong>
    <%= @usuario.email %>
    <br>
    <strong>Saldo:</strong>
    <%= number_to_currency(@usuario.saldo, {:precision => 0, :unit => "Bs ", :delimiter => "."}) %>
    <% recarga.user_id = @usuario.id %>
  <% end %>
  <br>

  <% recarga.referencia = "PRC#{Time.now.strftime("%j%H%M%S%L")}" if recarga.referencia == nil %>

  <strong>Referencia:</strong>
  <%= recarga.referencia %>
  <br>
  <%= f.hidden_field :referencia %>
  <%= f.hidden_field :user_id  %>
  <br>

  <div class="field">
    <%= f.label :monto_bs %>
    <%= f.number_field :monto_bs %>
  </div>

  <div class="field">
    <%= f.label :comentarios %>
    <%= f.text_area :comentarios %>
  </div>
  <button class="btn btn-primary">Recargar</button>

<% end %>

app/views/recargas/edit.html.erb
<div class="col-lg-3"></div>
<div class="col-lg-6 well">

<h1>Ajustar recarga</h1>

<%= render 'form', recarga: @recarga %>

<br>
<%= link_to 'Mostrar', @recarga %> |
<%= link_to 'Lista de pre-recargas', recargas_path %>

</div>

app/views/recargas/index.html.erb
<div class="col-lg-3"></div>
<div class="col-lg-6 well">

<h1>Recargas</h1>

<table>
  <thead>
    <tr>
      <th>Usuario</th>
      <th>Monto bs</th>
      <th>Fecha cargado</th>
      <th>Fecha aplicado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recargas.each do |recarga| %> 
      <% nombre = 'campaña' %>
      <% usuario = User.find(recarga.user_id) if recarga.user_id != 999999 %>
      <% nombre = usuario.username if recarga.user_id != 999999 %>
      <tr>

        <% if recarga.user_id != 999999 %>
          <td><%= link_to nombre, usuario_path(usuario) %></td>
        <% else %>
          <td><%= nombre %></td>
        <% end %>



        <td><%= number_to_currency(recarga.monto_bs, {:precision => 0, :unit => "Bs ", :delimiter => "."})%></td>
        <td><%= recarga.created_at.try(:strftime, "%m/%d/%Y %I:%M%p")  %></td>
        <td><%= recarga.f_aplicado.try(:strftime, "%m/%d/%Y %I:%M%p")  %></td>
        <td><%= link_to 'Mostrar', recarga %></td>
        <% if !recarga.f_aplicado %>
          <td><%= link_to 'Ajustar', edit_recarga_path(recarga) %></td>
          <td><%= link_to 'Aplicar', aplicar_path(recarga) %></td>
          <td><%= link_to 'Borrar', recarga, method: :delete, data: { confirm: 'Esta seguro???' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

</div>

app/views/recargas/new.html.erb
<div class="col-lg-3"></div>
<div class="col-lg-6 well">

<h1>Recargar</h1>

<%= render 'form', recarga: @recarga %>
<br>

</div>

app/views/recargas/recargar.html.erb
<div class="col-lg-3"></div>
<div class="col-lg-6 well">

<h1>Recargar</h1>

<%= render 'form', recarga: @recarga %>
<br>

</div>

app/views/recargas/show.html.erb
<div class="col-lg-3"></div>
<div class="col-lg-6 well">

  <h2>Detalle de la recarga</h2>
  <% if @usuario %>
    <strong>Nombre:</strong>
    <%= @usuario.name %>
    <br>
    <strong>Usuario:</strong>
    <%= @usuario.username %>
    <br>
    <strong>Correo:</strong>
    <%= @usuario.email %> 
    <br>
    <strong>Saldo del usuario:</strong>
    <%= number_to_currency(@usuario.saldo, {:precision => 0, :unit => "Bs ", :delimiter => "."}) %>
  <% else %>
    <strong>Saldo de la campaña:</strong><br>
    Ver barra de navegación
  <% end %>

  <br>
  <strong>Monto de la recarga:</strong>
  <%= number_to_currency(@recarga.monto_bs, {:precision => 0, :unit => "Bs ", :delimiter => "."}) %>
  <br>
  <strong>Referencia:</strong>
  <%= @recarga.referencia %>
  <br>
  <strong>Fecha creada:</strong>
  <%= @recarga.created_at.try(:strftime, "%m/%d/%Y %I:%M%p")  %>
  <br>
  <strong>Fecha aplicada:</strong>
  <%= @recarga.f_aplicado.try(:strftime, "%m/%d/%Y %I:%M%p")  %>
  <br>
  <strong>Comentarios:</strong>
  <%= @recarga.comentarios %>
  <br>
  <br>
  

<%= link_to 'Ajustar pre-recarga', edit_recarga_path(@recarga) %> |
<%= link_to 'Lista de pre-recargas', recargas_path %>

</div>

app/views/recargas/usuario.html.erb
<div class="col-lg-3"></div>
<div class="col-lg-6 well">


  <center><h2><%= "Detalle de usuario"  %></h2></center>

  <strong>Nombre:</strong>
  <%= @usuario.name %>
  <br>
  <strong>Usuario:</strong>
  <%= @usuario.username %>
  <br>
  <strong>Correo:</strong>
  <%= @usuario.email %>
  <br>
  <strong>Saldo:</strong>
  <%= number_to_currency(@usuario.saldo, {:precision => 0, :unit => "Bs ", :delimiter => "."}) %>
  <br>

  <strong>"Veces que se ha logeado:"</strong>
  <%= @usuario.sign_in_count %>
  <br>
  <strong>"Ultima vez que entró:"</strong>
  <%= @usuario.last_sign_in_at.try(:strftime, "%m/%d/%Y %I:%M%p") %>
  <br>
  <strong>"Ultima IP con la que entró:"</strong>
  <%= @usuario.last_sign_in_ip %>
  <br><br>
  <td> <%= button_to 'Pre-recargar saldo', recargar_path(@usuario.id), :class => "btn btn-warning", method: :get %></td>
</div>

app/views/recargas/usuarios.html.erb
<div class="col-lg-3"></div>
<div class="col-lg-6 well">

  <p id="notice"><%= notice %></p>

  <% s = 's'; s = '' if @total == 1 %>
  <table style="width:100%">
    <tr>
      <th style="text-align: left" ><h1><%= "#{@total} Usuario#{s}" %></h1></th>
      <th style="text-align: right" ><%= button_to 'Invitar a un usuario', invitar_path, :class => "btn btn-primary", method: :get %></th>
    </tr>
  </table>
  <br>
  <h5><%= "(Ver detalle del usuario al hacer CLIC en nombre, usuario, correo o saldo)" %></h5>

<table>
  <thead>
    <tr>
      <th style="text-align: center">Nombre</th>
      <th style="text-align: center">Usuario</th>
      <th style="text-align: center">Correo</th>
      <th style="text-align: center">Saldo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= link_to usuario.name, usuario_path(usuario) %></td>
        <td><%= link_to usuario.username, usuario_path(usuario) %></td>
        <td><%= link_to usuario.email, usuario_path(usuario) %></td>
        <td style="text-align: right"><%= link_to number_to_currency(usuario.saldo, {:precision => 0, :unit => "Bs ", :delimiter => "."}), usuario_path(usuario) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

</div>