config/routes.rb
Rails.application.routes.draw do
# get 'recibir/sms'

  get  'archivos/cargar'
  post 'archivos/cargar'
  post 'archivos/borrar'
# devise_for :users
  devise_for :users, controllers: { invitations: "invitations" }
  authenticated :user do
    root to: "mensajes#new", as: "entrada"
  end
  unauthenticated :user do
    root 'pagina#index'
  end
  resources :recargas
  resources :contactos
  resources :grupos
  resources :users, except: [:new, :create]
  resources :mensajes
  resources :directos, except: [:index, :show, :edit, :update, :destroy]

  post  '/mensajes/:id'          => 'mensajes#grupo',      as: 'mgrupo'
  post  '/enviar/:id'            => 'mensajes#enviar',     as: 'enviar'
  get   '/alcance/:id'           => 'mensajes#alcance',    as: 'alcance'
  match '/invitar/'              => 'users#invitar',       via: [:get, :post]
  get   '/usuarios/'             => 'recargas#usuarios'
  get   '/recargar/:id'          => 'recargas#recargar',   as: 'recargar'
  get   '/aplicar/:id'           => 'recargas#aplicar',    as: 'aplicar'
  get   '/recibir/'              => 'recibir#sms',         as: 'recibir'
  get   '/usuario/:id'           => 'recargas#usuario',    as: 'usuario'
  get   '/usar_sms/'             => 'pagina#usar_sms'
  get   '/terminos_condiciones/' => 'pagina#terminos_condiciones'
  get   '/diccionario/'          => 'entrada#diccionario' 
  get   '/premisas/'             => 'entrada#premisas' 
  get   '/horario_sugerido/'     => 'entrada#horario_sugerido' 
  get   '/horario_grafica/'      => 'entrada#horario_grafica' 
  get   '/horario_grafica100/'   => 'entrada#horario_grafica100' 
end

app/views/parciales/_devise_form_errors.html.erb
<% if resource.errors.any? %>
  <div class="alert alert-danger alert-dismissable">
  	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= resource.errors.full_messages.first %>
  </div>
<% end %>

app/views/parciales/_error_message.html.erb
<% if error_message %>
  <div class="alert alert-dismissable alert-fixed alert-info">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= error_message %>
  </div>
<% end %>

app/views/parciales/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "Mensajes", root_url, class: "navbar-brand" %>
    </div>
    <% if user_signed_in? %>
      <div class="nav navbar-nav navbar-left">
        <li>
           <ul class="nav navbar-nav">
           <li class="active dropdown">
           <a class="dropdown-toggle" data-toggle="dropdown" href="#">Gestión
           <ul class="dropdown-menu" role="menu">
             <strong><li class="dropdown-header">Operaciones</li></strong>
             <li><%= link_to 'Contactos', contactos_path %></li>
             <li><%= link_to 'Grupos', grupos_path %></li>
             <li><%= link_to 'Cargar Archivo', archivos_cargar_path %></li>
             <li><%= link_to 'Pre cargar saldo', recargar_path(current_user.id) %></li>
             <li class="divider"></li>
             <strong><li class="dropdown-header">De interés</li></strong>
             <li><%= link_to 'Diccionario', diccionario_path %></li>
             <li><%= link_to 'Premisas', premisas_path %></li>
             <li><%= link_to 'Términos y Condiciones', terminos_condiciones_path %></li>
             <li><%= link_to 'Horario sugerido', horario_sugerido_path %></li>
            <% if @modo == 'demo' %>
              <li><%= link_to 'Invitar a:', invitar_path %></li>
            <% else %>
              <li><%= link_to 'Invitar a:', invitar_path if current_user.id == 1 %></li>
            <% end %>
            <% if current_user.email == 'rrg1459@hotmail.com' || current_user.email == 'rafa@com' %>
              <li class="divider"></li>
              <strong><li class="dropdown-header">Gestionar</li></strong>
              <li><%= link_to 'Usuarios', usuarios_path %></li>
              <li><%= link_to 'Pre recargar campaña', new_recarga_path %></li>
              <li><%= link_to 'Lista de recargas', recargas_path %></li>
            <% end %>
           </ul>
           <li class="dropdown">
           <a class="dropdown-toggle" data-toggle="dropdown" >saldo: <b><%= number_to_currency(@saldo, {:precision => 0, :unit => "Bs ", :delimiter => "."})%></b>
           <ul class="dropdown-menu" role="menu">
             <li><a href="#"><%= number_to_currency(@valor, {:precision => 0, :unit => "Bs ", :delimiter => "."})%><%= " x SMS"%></a></li>
             <li><a href="#"><%= "Cupo: #{@cupo} SMS"%></a></li>
           </ul>
        </li>
        <li> <%= button_to 'SMS', new_directo_url, :class => "btn btn-default navbar-btn", method: :get %></li>
        <li class="dropdown">
           <a class="dropdown-toggle" data-toggle="dropdown" >modo: <b><%= "#{@modo}" %></b>
           <ul class="dropdown-menu" role="menu"></ul>
      </div>
      <div class="nav navbar-nav navbar-right">
         <% nombre = current_user.name.split(" ") %>
         <b><%= link_to "#{nombre[0].capitalize}", edit_user_path(current_user) %></b>&nbsp;
         <%= link_to destroy_user_session_url, method: :delete do %>
            <button class="btn btn-primary navbar-btn">Cerrar</button>
         <% end %>
      </div>
    <% end %>
  </div>
</nav>