config/routes.rb
Rails.application.routes.draw do
# get 'recibir/sms'

  get  'archivos/cargar'
  post 'archivos/cargar'
  post 'archivos/borrar'
# devise_for :users
  devise_for :users, controllers: { invitations: "invitations" }
  authenticated :user do
    root to: "mensajes#new", as: "entrada"
  end
  unauthenticated :user do
    root 'pagina#index'
  end
  resources :recargas
  resources :contactos
  resources :grupos
  resources :users, except: [:new, :create]
  resources :mensajes
  resources :directos, except: [:index, :show, :edit, :update, :destroy]

  post  '/mensajes/:id'          => 'mensajes#grupo',      as: 'mgrupo'
  post  '/enviar/:id'            => 'mensajes#enviar',     as: 'enviar'
  get   '/alcance/:id'           => 'mensajes#alcance',    as: 'alcance'
  match '/invitar/'              => 'users#invitar',       via: [:get, :post]
  get   '/usuarios/'             => 'recargas#usuarios'
  get   '/recargar/:id'          => 'recargas#recargar',   as: 'recargar'
  get   '/aplicar/:id'           => 'recargas#aplicar',    as: 'aplicar'
  get   '/recibir/'              => 'recibir#sms',         as: 'recibir'
  get   '/usuario/:id'           => 'recargas#usuario',    as: 'usuario'
  get   '/usar_sms/'             => 'pagina#usar_sms'
  get   '/terminos_condiciones/' => 'pagina#terminos_condiciones'
  get   '/diccionario/'          => 'entrada#diccionario' 
  get   '/premisas/'             => 'entrada#premisas' 
  get   '/horario_sugerido/'     => 'entrada#horario_sugerido' 
  get   '/horario_grafica/'      => 'entrada#horario_grafica' 
  get   '/horario_grafica100/'   => 'entrada#horario_grafica100' 
end

app/models/grupo.rb
class Grupo < ApplicationRecord
  has_and_belongs_to_many :contactos
  has_and_belongs_to_many :mensajes

  after_create   :actualizar_grupo
  after_update   :actualizar_grupo

	  validates :nombre,      presence: { message: "en blanco" }, 
                length:   {minimum: 3, :message => "debe tener por lo menos 3 letras"},
                uniqueness: { case_sensitive: false, message: "de grupo ya existe" }

  def nombre_cantidad
    "#{nombre}, #{cantidad_contactos} contactos"
  end

end

app/controllers/grupos_controller.rb
class GruposController < ApplicationController
  before_action :set_grupo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :saldo_sms
  before_action :modo

  # GET /grupos
  # GET /grupos.json
  def index
    if @modo == 'campanna'
      @grupos = Grupo.all
    else
      @grupos = Grupo.where(user_id: current_user.id)
    end
    @total = @grupos.length
  end

  # GET /grupos/1
  # GET /grupos/1.json
  def show
    grupo = {"grupos_id_in_any"=>[params[:id].to_s]}
    if @modo == 'campanna'
      @buscar = Contacto.search(grupo)
    else
      @buscar = Contacto.where(user_id: current_user.id).search(grupo)
    end
    @contactos = @buscar.result(distinct: true).order("numero")
  end

  # GET /grupos/new
  def new
    @grupo = Grupo.new
    agrupar
  end

  # GET /grupos/1/edit
  def edit
    agrupar
  end

  # POST /grupos
  # POST /grupos.json
  def create
    @grupo = Grupo.new(grupo_params)
    @grupo.user_id = current_user.id

    respond_to do |format|
      if @grupo.save
        format.html { redirect_to @grupo, notice: 'Grupo creado' }
        format.json { render :show, status: :created, location: @grupo }
      else
        format.html { render :new }
        format.json { render json: @grupo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grupos/1
  # PATCH/PUT /grupos/1.json
  def update
    @grupo.user_id = current_user.id
    respond_to do |format|
      if @grupo.update(grupo_params)
        format.html { redirect_to @grupo, notice: 'Grupo editado' }
        format.json { render :show, status: :ok, location: @grupo }
      else
        format.html { render :edit }
        format.json { render json: @grupo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grupos/1
  # DELETE /grupos/1.json
  def destroy
    @grupo.destroy
    respond_to do |format|
      format.html { redirect_to grupos_url, notice: 'Grupo borrado' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grupo
      @grupo = Grupo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grupo_params
      params.require(:grupo).permit(:nombre, contacto_ids:[])
    end

    def agrupar
      if @modo == 'campanna'
        @contacto_cb = Contacto.all 
      else
        @contacto_cb = Contacto.where(user_id: current_user.id).order("numero")
      end
    end

end

app/helpers/grupos_helper.rb
module GruposHelper
end

app/views/grupos/_form.html.erb
<%= form_for(grupo) do |f| %>

  <% if grupo.errors.any? %>
    <%= render 'parciales/error_message', error_message: grupo.errors.full_messages.first %>
  <% end %>

  <button class="btn btn-primary">Guardar</button>

  <br>
  <br>

  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre, id: :grupo_nombre, class: "mostrar form-control", style: "width: 340px;" %>
  </div>
  <table>
    <br>
    <strong>
    <h4><%= f.label "Seleccionar contactos para agregar al grupo" %></h4><br />
    </strong>
    <%= f.collection_check_boxes :contacto_ids, @contacto_cb.order("numero"), :id, :numero_nombre do |b| %>
      <div class="collection-check-box">
        <tr>
          <td><%= b.check_box %></td>
          <td><%= b.label  %></td>
        </tr>
      </div>
    <% end %>
  </table>
  <br>
<% end %>

app/views/grupos/edit.html.erb
<div class="col-lg-3"></div>
<div class="col-lg-6 well">
  <h1>Editando Grupo</h1>
  <%= render 'form', grupo: @grupo %>
  <table>
    <th>
      <td> <%= button_to 'Listado de Grupos', grupos_path, :class => "btn btn-info", method: :get %></td>
      <td> <%= button_to 'Mostrar', grupo_path, :class => "btn btn-success", method: :get %></td>
    </th>
  </table>
</div>

app/views/grupos/index.html.erb
<div class="col-lg-3"></div>
  <div class="col-lg-6 well">
  <% s = 's'; s = '' if @total == 1 %>
  <table style="width:100%">
    <tr>
      <th style="text-align: left" ><h1><%= "#{@total} Grupo#{s}" %></h1></th>
      <th style="text-align: right" ><%= button_to 'Nuevo Grupo', new_grupo_path, :class => "btn btn-primary", method: :get %></th>
    </tr>
  </table>
  <% if @total > 0 %>
    <br><h5><%= "(Se puede ver detalle del grupoal hacer CLIC en el en el nombre)" %></h5><br>
    <table>
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Contactos</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @grupos.each do |grupo| %>
          <% cg = ContactosGrupo.where(grupo_id: grupo.id) %>
          <% contactos = cg.length %>
          <tr>
            <td><%= link_to grupo.nombre, grupo %></td>
            <td><%= contactos %></td>
            <td style="text-align: center" ><%= button_to 'Borrar', grupo, :class => "btn btn-danger", method: :delete, data: { confirm: "Esta usted seguro que quiere borrar al grupo #{grupo.nombre}???" } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br>
  <% end %>
</div>

app/views/grupos/new.html.erb
<div class="col-lg-3"></div>
<div class="col-lg-6 well">
  <h1>Nuevo Grupo</h1>
  <%= render 'form', grupo: @grupo %>
  <%= button_to 'Listado de Grupos', grupos_path, :class => "btn btn-info", method: :get %>
</div>

app/views/grupos/show.html.erb
<div class="col-lg-3"></div>
<div class="col-lg-6 well">
  <table style="width:100%">
    <tr>
      <th style="text-align: left" ><h1>Grupo</h1></th>
      <th style="text-align: right" ><%= button_to 'Nuevo Grupo', new_grupo_path, :class => "btn btn-primary", method: :get %></th>
    </tr>
  </table>
  <p>
    <% s = 's'; s = '' if @grupo.cantidad_contactos == 1 %>
    <h3><strong><%= "#{@grupo.nombre}," %></strong> <%= "tiene #{@grupo.cantidad_contactos} contacto#{s}" %></h3>
  </p>
  <% num = @contactos.length %>
  <% if num > 0 %>
    <h4><%= "Lista de contactos" %></h4>
    <h5><%= "(Se puede ver detalle del contacto al hacer CLIC en el número o en el nombre)" %></h5>
    <table>
      <thead>
        <tr>
          <th style="text-align: center" >Numero</th>
          <th style="text-align: center" >Nombre</th>
          <th style="text-align: center" >Archivo</th>
          <th style="text-align: center" >Todos los grupos de este contacto</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @contactos.each do |contacto| %>
          <tr>
            <td><%= link_to "(0#{contacto.numero[0,3]})#{contacto.numero[3,3]}-#{contacto.numero[6,7]}", contacto %></td>
            <td><%= link_to contacto.nombre, contacto %></td>
            <td><%= contacto.archivo %></td>
            <td><%= contacto.grupos.map(&:nombre).sort.join(", ") %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br>
    <br>
  <% end %>
  <table>
  <th>
     <td> <%= button_to 'Listado de Grupos', grupos_path, :class => "btn btn-info", method: :get %></td>
     <td> <%= button_to 'Editar', edit_grupo_path, :class => "btn btn-success", method: :get %></td>
  </th>
  </table>
</div>