config/routes.rb
Rails.application.routes.draw do
# get 'recibir/sms'

  get  'archivos/cargar'
  post 'archivos/cargar'
  post 'archivos/borrar'
# devise_for :users
  devise_for :users, controllers: { invitations: "invitations" }
  authenticated :user do
    root to: "mensajes#new", as: "entrada"
  end
  unauthenticated :user do
    root 'pagina#index'
  end
  resources :recargas
  resources :contactos
  resources :grupos
  resources :users, except: [:new, :create]
  resources :mensajes
  resources :directos, except: [:index, :show, :edit, :update, :destroy]

  post  '/mensajes/:id'          => 'mensajes#grupo',      as: 'mgrupo'
  post  '/enviar/:id'            => 'mensajes#enviar',     as: 'enviar'
  get   '/alcance/:id'           => 'mensajes#alcance',    as: 'alcance'
  match '/invitar/'              => 'users#invitar',       via: [:get, :post]
  get   '/usuarios/'             => 'recargas#usuarios'
  get   '/recargar/:id'          => 'recargas#recargar',   as: 'recargar'
  get   '/aplicar/:id'           => 'recargas#aplicar',    as: 'aplicar'
  get   '/recibir/'              => 'recibir#sms',         as: 'recibir'
  get   '/usuario/:id'           => 'recargas#usuario',    as: 'usuario'
  get   '/usar_sms/'             => 'pagina#usar_sms'
  get   '/terminos_condiciones/' => 'pagina#terminos_condiciones'
  get   '/diccionario/'          => 'entrada#diccionario' 
  get   '/premisas/'             => 'entrada#premisas' 
  get   '/horario_sugerido/'     => 'entrada#horario_sugerido' 
  get   '/horario_grafica/'      => 'entrada#horario_grafica' 
  get   '/horario_grafica100/'   => 'entrada#horario_grafica100' 
end

app/models/mensaje.rb
class Mensaje < ActiveRecord::Base

  has_and_belongs_to_many :grupos
  has_and_belongs_to_many :contactos

  require 'net/http'
  require 'uri'
  require 'openssl'
  OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE

  self.per_page = 20

  belongs_to :user

  validates :texto,
  presence: { message: "en blanco" },
  length: { maximum: 160, :message => "muy largo" }

  counter_culture :user
end

private
  def actualizar_grupos(di)
    contador = 0 
    vector = []
    gm = GruposMensaje.where(mensaje_id: di)
    gm.each do |gml|
      grp = Grupo.find(gml.grupo_id)
      cg = ContactosGrupo.where(grupo_id: grp.id) 
      cg.each do |cgl|
        contacto = Contacto.find(cgl.contacto_id)
        vector[contador] = contacto.id
        contador += 1
      end
    end
    vector = vector.sort.uniq
    total = vector.length
    mensaje = Mensaje.find(di)
    mensaje.update_columns(cantidad_contactos: total)
    mensaje.contactos.delete_all
    vector.each do |id_contacto|
      ContactosMensaje.create( { "mensaje_id" => di, "contacto_id" => id_contacto })
    end
  end

  def enviar_mensaje(di)
    total = 0
    mensaje = Mensaje.find(di)
    @sms = mensaje.texto
    cm = ContactosMensaje.where(mensaje_id: di)

    ciclo = 100 # maximo 100 por lista que es lo que permite la API

    todos = cm.length
    @uri = URI.parse("https://api.textveloper.com/sms/enviar/") 
    @uri = URI.parse("https://api.textveloper.com/sms/enviar/lista/") if todos > ciclo
    @request = Net::HTTP::Post.new(@uri) 
    contactos = []
    cm.each do |c|
      contacto = Contacto.find(c.contacto_id)
      tlfs = "0#{contacto.numero}"
      contactos[total] = tlfs
      total += 1
    end
    if todos > ciclo
      (0..todos - 1 ).each_slice(ciclo) do |x|
        @tlf = x.map { |_| contactos[_] }.join(",")
      end
    else
      numeros = (0..todos - 1).map { |num| num }
      @tlf = numeros.map { |_| contactos[_] }.join(",")
    end
    modo
    enviar_sms
    total = total * @valor.to_i
    pedir_saldo
    if @modo == 'campanna'
      saldo = Saldo.find_by(usuario_id: 999999)
      saldo.update_columns(saldo: (@saldo - total)) 
    else
      @saldo = current_user.saldo
      usuario = User.find(current_user.id)
      usuario.update_columns(saldo: @saldo - total)
    end  
    mensaje.enviado_por_id = current_user.id
    mensaje.f_enviado = Time.now
    mensaje.save
    @mensaje = 'Mensaje enviado' 
  end

  def enviar_sms
=begin
    puts '======================'
    puts '-----enviar SMS-------'
    puts "uri: #{@uri}"
    puts "tlf: #{@tlf}"
    puts "sms: #{@sms}"
    puts "request: #{@request}"
    puts '-----enviar SMS-------'
    puts '======================'
=end
#=begin
    @request.set_form_data(
      "telefono" => @tlf,
      "mensaje" => "#{@sms}",
      "cuenta_token" => ENV["CUENTA_TOKEN"],
      "aplicacion_token" => ENV["APLICACION_TOKEN"]
    )
    req_options = { use_ssl: @uri.scheme == "https" }
    response = Net::HTTP.start(@uri.hostname, @uri.port, req_options) do |http|
      http.request(@request)
    end
    puts "response.code..: #{response.code}"
    puts "response.body..: #{response.body}"
#=end

  end

  def capacidad_demo(di)
    @mensaje = nil
    alto = 0
    gm = GruposMensaje.where(mensaje_id: di)
    gm.each do |gml|
      grp = Grupo.find(gml.grupo_id)
      cg = ContactosGrupo.where(grupo_id: grp.id) 
      contactos = cg.length
      alto = contactos if alto < contactos
    end
    grupos = gm.length   
    @demo = true
    @demo = false if alto > 3 || grupos > 2 
    @mensaje = "Estás en modo demo: Máximo 3 contactos por grupo" if alto > 3 
    @mensaje = "Estás en modo demo: Máximo 2 grupos  X mensaje" if grupos > 2 
  end

  def capacidad_saldo(di)
    if di == 888888
      total = 1
    else
      total = (ContactosMensaje.where(mensaje_id: di)).length
    end
    total *= @valor.to_i
    modo
    pedir_saldo
    @capacidad = true
    @capacidad = false if total > @saldo
    @mensaje = 'El alcance supera su saldo, recargue su saldo para envíar este mensaje' if total > @saldo
  end

  def pedir_saldo
    if @modo == 'campanna'
      saldo = Saldo.find_by(usuario_id: 999999)
      @saldo = saldo.saldo
    else
      @saldo = current_user.saldo
    end  
  end

app/controllers/mensajes_controller.rb
class MensajesController < ApplicationController

  before_action :set_mensaje, only: [:show, :alcance, :enviar, :edit, :update, :grupo, :destroy]
  before_action :authenticate_user!
  before_action :saldo_sms
  before_action :modo

  def new
    @mensaje = Mensaje.new
    agrupar
  end

  def create
    @mensaje = Mensaje.new(mensaje_params)
    @mensaje.user_id = current_user.id
    respond_to do |format|
      if @mensaje.save
        format.html { redirect_to new_mensaje_path, notice: 'Mensaje creado' }
      else
        agrupar
        format.html { render :new }
      end
    end
  end

  def show
    buscar_nombre
  end

  def alcance
    buscar_nombre
    mensaje = {"mensajes_id_in_any"=>[params[:id].to_s]}
    if @modo == 'campanna'
      @buscar = Contacto.search(mensaje)
    else  
      @buscar = Contacto.where(user_id: current_user.id).search(mensaje)
    end
    @contactos = @buscar.result(distinct: true).order("numero")
    @total = (@contactos = @buscar.result(distinct: true).order("numero")).length
  end

  def enviar
    capacidad_saldo(params[:id])
    if @capacidad 
      if @modo == 'demo'
        capacidad_demo(params[:id])
        enviar_mensaje(params[:id]) if @demo
      else
        enviar_mensaje(params[:id])
      end
    end
    redirect_to mensaje_path, notice: @mensaje
  end

  def edit
  end

  def update
    respond_to do |format|
      if @mensaje.update(mensaje_params)
        format.html { redirect_to '/', notice: 'mensaje editado' }
      else
        format.html { render :edit }
        format.json { render json: @contacto.errors, status: :unprocessable_entity }
      end
    end
  end

  def grupo
    respond_to do |format|
      if @mensaje.update(mensaje_params)
        actualizar_grupos(params[:id])
        format.html { redirect_to mensaje_path, notice: 'Alcance actualizado' }
      else
        format.html { render :show }
        format.json { render json: @contacto.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @mensaje.destroy
    respond_to do |format|
      format.html { redirect_to '/', notice: 'Mensaje borrado' }
    end
  end

  def buscar_nombre
    if User.exists?(@mensaje.enviado_por_id)
      nombre = User.find(@mensaje.enviado_por_id)
      @enviado_por = nombre.name.split(" ")
    end
  end

  private
  def set_mensaje
    @mensaje = Mensaje.find(params[:id])
  end
  
  def mensaje_params
    params.require(:mensaje).permit(:texto, :cantidad_contactos, grupo_ids:[])
  end

  def agrupar
    if @modo == 'campanna'
      @mensajes = Mensaje.all.order('updated_at DESC')
    else
      @mensajes = Mensaje.where(user_id: current_user.id).order('updated_at DESC')
    end
  end

end

app/helpers/mensajes_helper.rb
module MensajesHelper
end

app/views/mensajes/_mensaje.html.erb
<div id="mensaje-<%= mensaje.id %>" class="micropost">
  <div class="content">
    <div class="post-content">
      <% nombre = mensaje.user.username.split(" ") %>
      <b><%= "#{nombre[0].capitalize}" %></b>
      <div class="mostrar alert alert-danger alert-dismissable">
        <button type="button" class="close" ></button>
        <%= mensaje.texto %>
      </div>
    </div>
    <% if mensaje.f_enviado %>
      <div class="right-content">
        <span><%= relative_time(mensaje.f_enviado) %></span>
      </div>
      <div class="right-content">
        <span><%= "Enviado: " %><strong><%= "#{mensaje.f_enviado.strftime("%d %b %Y")}" %></strong></span>
      </div>
    <% else %>
      <div class="right-content">
        <span><%= relative_time(mensaje.updated_at) %></span>
      </div>
      <div class="right-content">
        <span><%= "Editado: " %><strong><%= "#{mensaje.updated_at.strftime("%d %b %Y")}" %></strong></span>
      </div>
    <% end %>
  </div>
  <div class="actions">
    <div class="actions-content">
      <% if !mensaje.f_enviado %>
        <%= link_to mensaje, class: 'btn btn-link',  title: 'enviar mensaje', 'data-toggle' => 'tooltip', 'data-placement' => 'bottom' do %>
          <i class="fa fa-cog fa-spin"></i>
        <% end %>
        <% if mensaje.user == current_user %>
          <%= link_to edit_mensaje_path(mensaje), class: 'btn btn-link',  title: 'editar mensaje', 'data-toggle' => 'tooltip', 'data-placement' => 'bottom' do %>
            <i class="fa fa-keyboard-o"></i>
          <% end %>
          <%= link_to mensaje, class: 'btn btn-link',  title: 'borrar mensaje', 'data-toggle' => 'tooltip', 'data-placement' => 'bottom', method: :delete, data: { confirm: "Esta usted seguro que quiere borrar este mensaje: #{mensaje.texto}???" } do %>
            <i class="fa fa-trash"></i>
          <% end %>
        <% end %>
      <% end %> 
      <% if mensaje.cantidad_contactos != 0 %>
        <% s = 's'; s = '' if mensaje.cantidad_contactos == 1 %>
        <%= link_to alcance_path(mensaje), class: 'btn-link',  title: 'Detalle del mensaje', 'data-toggle' => 'tooltip', 'data-placement' => 'bottom' do %>
          <span><%= "Alcance: #{mensaje.cantidad_contactos} contacto#{s}" %></span>
        <% end %>
      <% end %>  
    </div>
  </div>
</div>





     

app/views/mensajes/_mensaje_nuevo.html.erb
<%= form_tag mensajes_path(parent_id: mensaje_id), method: :post do %>
  <div class="form-group">
    <%= text_area_tag "mensaje[texto]", @mensaje.texto, class: "mostrar form-control", placeholder: "Escribe un mensaje hasta 160 caracteres" %>
  </div>

  <div class="form-group">
    <%= button_tag id: "mensaje", class: "btn btn-primary" do %>
       Guardar
    <% end %>
    <% largo = 0 %>
    <% largo = @mensaje.texto.length if @mensaje.texto != nil %>
    <% contador = 160 - largo %>
    <div class="pull-right">
      <span id="mensaje-count"><%= "#{contador}" %></span>
    </div>
  </div>
<% end %>

<div id="mensaje-error">
  <%= render 'parciales/error_message', error_message: nil %>
</div>

app/views/mensajes/alcance.html.erb
<div class="col-lg-3"></div>
<div class="col-lg-6 well">
  <p>
    <h4><center><strong><%= "Detalle del mensaje" %></strong></center></h4>
  </p>
    <div class="mostrar alert alert-danger alert-dismissable">
      <button type="button" class="close" ></button>
      <%= @mensaje.texto %>
    </div> 
    <% largo = @mensaje.texto.length %>
    <div class="pull-right"> 
      <span id="mensaje-count"><%= "#{largo} caracteres" %></span>
    </div>
    <% nombre = @mensaje.user.name.split(" ") %>
    <h5><%= "Creado por #{nombre[0].capitalize} el " %><strong><%= @mensaje.created_at.strftime("%d %b %Y %I:%M %p") %></strong></h5>
    <% if @mensaje.f_enviado %>
      <h5><%= "Enviado por #{@enviado_por[0].capitalize} el " %><strong><%= @mensaje.f_enviado.strftime("%d %b %Y %I:%M %p") %></strong></h5>
    <% end %>
    <br>
    <% if @total == 0 %>
      <center><h4><%= "Se han borrado todos los contactos enviados a este mensaje" %></h4><br></center> 
    <% else %>
      <% num = @mensaje.cantidad_contactos - @total %>
      <% if num > 0 %>
        <% n = 'n'; s = 's'; s, n = '' if num == 1 %>
        <h5><u><%= "Se ha#{n} borrado #{num} contacto#{s} a este mensaje" %></u></h5><br>
      <% end %>
      <% if @mensaje.cantidad_contactos == 1 %>
        <h5><%= "Detalle del contacto" %></h5><br>
      <% else %>
        <h5><%= "Lista de los #{@mensaje.cantidad_contactos} contactos" %></h5><br>
      <% end %>
      <h5><%= "(Se puede ver detalle del contacto al hacer CLIC en el número o en el nombre)" %></h5>
      <table>
        <thead>
          <tr>
            <th style="text-align: center" >Numero</th>
            <th style="text-align: center" >Nombre</th>
            <th style="text-align: center" >Todos los grupos de este contacto</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @contactos.each do |contacto| %>
            <tr>
              <td><%= link_to "(0#{contacto.numero[0,3]})#{contacto.numero[3,3]}-#{contacto.numero[6,7]}", contacto %></td>
              <td><%= link_to contacto.nombre, contacto %></td>
              <td><%= contacto.grupos.map(&:nombre).sort.join(", ") %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br><br>
    <% end %>
  <table>
  <th>
     <td> <%= button_to 'Pagina Principal', '/', :class => "btn btn-default", method: :get %></td>
  </th>
  </table>
</div>

app/views/mensajes/edit.html.erb
<div class="col-lg-3"></div>
<div class="col-lg-6 well">
  <%= form_for(@mensaje) do |f| %>
    <% if @mensaje.errors.any? %>
        <%= render 'parciales/error_message', error_message: @mensaje.errors.full_messages.first %>
    <% end %>  
    <div class="field">
      <%= f.label "Modificar Texto" %>
      <%= f.text_area :texto, class: "mostrar form-control", size: "128x2", placeholder: "Escribe un mensaje hasta 160 caracteres" %>
    </div>
    <br>
    <% largo = 160 - @mensaje.texto.length %>
    <%= button_tag id: "mensaje", class: "btn btn-primary" do %>
       Guardar
    <% end %>
    <div class="pull-right"> 
      <span id="mensaje-count"><%= "#{largo}" %></span>
    </div>
  <% end %>
  <br>
</div>

app/views/mensajes/edit_grupo.html.erb
<div class="col-lg-3"></div>
<div class="col-lg-6 well">
  <%= form_for(@mensaje) do |f| %>
    <% if @mensaje.errors.any? %>
        <%= render 'parciales/error_message', error_message: @mensaje.errors.full_messages.first %>
    <% end %>  
    <div class="field">
      <%= f.label "Modificar Texto" %>
      <%= f.text_area :texto, class: "mostrar form-control", size: "128x2", placeholder: "Escribe un mensaje hasta 160 caracteres" %>
    </div>
    <div class="mostrar alert alert-danger alert-dismissable">
      <button type="button" class="close" ></button>
      <%= @mensaje.texto %>
    </div>
    <br>
    <% largo = 160 - @mensaje.texto.length %>
    <%= button_tag id: "mensaje", class: "btn btn-primary" do %>
       Guardar
    <% end %>
    <table>
      <th>
        <td> <%= button_to 'Enviar',  mensaje_path, :class => "btn btn-danger", method: :get %></td>
        <td> <%= button_to 'Guardar', mensaje_path, :class => "btn btn-primary", method: :get %></td>
        <td> <%= button_to 'Guardar get', mgrupo_path(@mensaje), :class => "btn btn-primary", method: :get %></td>
        <td> <%= button_to 'Guardar post', mgrupo_path(@mensaje), :class => "btn btn-primary", method: :post %></td>
        <td> <%= button_to 'Regresar', '/', :class => "btn btn-default", method: :get %></td>
      </th>
    <div class="pull-right"> 
      <span id="mensaje-count"><%= "#{largo}" %></span>
    </div>
    <br>
    <table>
      <strong>
      <h4><%= "Seleccionar grupos para enviar este mensaje" %></h4>
      <h5><%= "(Después de seleccionar se debe guardar para envíar)" %></h5><br />
      </strong>
      <%= f.collection_check_boxes :grupo_ids, @grupo, :id, :nombre do |b| %>
        <div class="collection-check-box">
          <tr>
            <td><%= b.check_box %></td>
            <td><%= b.label %></td>
          </tr>
        </div>
      <% end %>
    </table>
    <br>
  <% end %>
  <br>
</div>

app/views/mensajes/new.html.erb
<div class="row">
  <div class="col-lg-3">
  </div>
  <div class="col-lg-6">
    <div class="row">
      <div class="col-lg-12">
        <div class="well">
          <% if @mensaje.errors.any? %>
            <%= render 'parciales/error_message', error_message: @mensaje.errors.full_messages.first %>
          <% end %>  
          <%= render 'mensaje_nuevo', mensaje_id: nil %>
        </div>
      </div>
    </div>
    <% @mensajes.each do |mensaje| %>
      <div class="row">
        <div class="col-lg-12">
          <div id="feed" class="well feed">
            <%= render(mensaje) %>
          </div>
        </div>
       </div>
    <% end %>
  </div>
</div>

app/views/mensajes/show.html.erb
<div class="col-lg-3"></div>
<div class="col-lg-6 well">
  <%= form_for :mensaje, url: mgrupo_path(@mensaje) do |f| %>
      <% if @mensaje.errors.any? %>
          <%= render 'parciales/error_message', error_message: @mensaje.errors.full_messages.first %>
      <% end %>  
        <%= f.label "Enviar Mensaje" %>
    <div class="mostrar alert alert-danger alert-dismissable">
      <button type="button" class="close" ></button>
      <%= @mensaje.texto %>
    </div>
      <% largo =  @mensaje.texto.length %>
      <div class="pull-right"> 
        <span id="mensaje-count"><%= "#{largo} caracteres" %></span>
      </div>
      <% s = 's'; s = '' if @mensaje.cantidad_contactos == 1 %>
      <%= link_to alcance_path(@mensaje), class: 'btn-link',  title: 'Detalle del mensaje', 'data-toggle' => 'tooltip', 'data-placement' => 'bottom' do %>
        <span><h5><%= "Alcance: #{@mensaje.cantidad_contactos} contacto#{s}" %></h5></span>
      <% end %>
      <% nombre = @mensaje.user.name.split(" ") %>
      <h5><%= "Creado por #{nombre[0].capitalize} el " %><strong><%= @mensaje.created_at.strftime("%d %b %Y %I:%M %p") %></strong></h5>
      <% if @mensaje.f_enviado %> 
        <h5><%= "Enviado por #{@enviado_por[0].capitalize} el " %><strong><%= @mensaje.f_enviado.strftime("%d %b %Y %I:%M %p") %></strong></h5>
      <% %>
      <% end %>
      <table>
        <th>
          <td><%= button_to '', '/', :class => "btn btn-link disabled", method: :get %></td>
          <% if @mensaje.cantidad_contactos == 0 || @mensaje.f_enviado %>
            <td><%= button_to 'Enviar', enviar_path(@mensaje), :class => "btn btn-danger disabled", method: :post %></td>        
          <% else %>
            <td><%= button_to 'Enviar', enviar_path(@mensaje), :class => "btn btn-danger", method: :post %></td>
          <% end %>
          <% if @mensaje.f_enviado %>
            <td>    
              <%= button_tag id: "mensaje", class: "btn btn-primary disabled" do %>
                Guardar
              <% end %>
            </td>
            <td> 
              <% if @mensaje.user == current_user %>
                <%= button_to edit_mensaje_path(@mensaje), :class => "btn btn-success disabled", method: :get do %>
                  <span class="fa fa-keyboard-o"></span> Editar
                <% end %>
              <% end %>
            </td>
            <% else %>
            <td>    
              <%= button_tag id: "mensaje", class: "btn btn-primary" do %>
                Guardar
              <% end %>
            </td>
            <td> 
              <% if @mensaje.user == current_user %>
                <%= button_to edit_mensaje_path(@mensaje), :class => "btn btn-success", method: :get do %>
                  <span class="fa fa-keyboard-o"></span> Editar
                <% end %>
              <% end %>
            </td>
          <% end %>
          <td> <%= button_to 'Regresar', '/', :class => "btn btn-default", method: :get %></td>
        </th>
      <br>
      <table>
        <strong>
        <h4><%= "Se sugiere guardar justo antes de enviar" %></h4>
        <h5><%= "(para tener actualizado el alcance de los contactos)" %></h5><br />
        </strong>
        <!%= f.collection_check_boxes :grupo_ids, Grupo.all, :id, :nombre_cantidad do |b| %>
        <%= f.collection_check_boxes :grupo_ids, Grupo.where(user_id: current_user.id), :id, :nombre_cantidad do |b| %>
          <div class="collection-check-box">
            <tr>
              <td><%= b.check_box %></td>
              <td><%= b.label %></td>
            </tr>
          </div>
        <% end %>
      </table>
      <br>
    <% end %>
    <br>
</div>

app/views/mensajes/show_grupo.html.erb
<div class="col-lg-3"></div>
<div class="col-lg-6 well">

	<h2>Mensaje</h2>
  <br>
  <h4>Texto</h4>
  <div class="mostrar alert alert-danger alert-dismissable">
  	<button type="button" class="close" ></button>
    <%= @mensaje.texto %>
  </div>
    <% if @mensaje.cantidad_contactos %>
      <h5><%= "Alcance: " %><strong><%= @mensaje.cantidad_contactos %></strong><%= " contactos" %></h5>
    <% end %>
    <h5><%= "Creado: " %><strong><%= @mensaje.created_at.strftime("%d %b %Y") %></strong></h5>
    <h5><%= "Editado: " %><strong><%= @mensaje.updated_at.strftime("%d %b %Y") %></strong></h5>
    <h5><%= "Lo creó: " %><strong><%= @mensaje.user.name %></strong></h5>
    <br>


  <%= form_for(@mensaje) do |f| %>

    <br>
    <table>
      <strong>
      <h4><%= "Seleccionar grupos para enviar este mensaje" %></h4>
      <h5><%= "(Después de seleccionar se debe guardar para envíar)" %></h5><br />
      </strong>
      <!%= f.collection_check_boxes :grupo_ids, Grupo.all, :id, :nombre do |b| %>
      <%= f.collection_check_boxes :grupo_ids, Grupo.where(user_id: current_user.id), :id, :nombre do |b| %>
        <div class="collection-check-box">
          <tr>
            <td><%= b.check_box %></td>
            <td><%= b.label %></td>
          </tr>
        </div>
      <% end %>
    </table>
    <br>



    
  	<table>
      <th>
        <td> <%= button_to 'Enviar',  mensaje_path, :class => "btn btn-danger", method: :get %></td>
        <td> <%= button_to 'Guardar', mensaje_path, :class => "btn btn-primary", method: :get %></td>










        <td> <%= button_to 'Guardar get', mgrupo_path(@mensaje), :class => "btn btn-primary", method: :get %></td>
        <td> <%= button_to 'Guardar post', mgrupo_path(@mensaje), :class => "btn btn-primary", method: :post %></td>








        <td> <%= button_to 'Regresar', '/', :class => "btn btn-default", method: :get %></td>
      </th>
    </table>



  <% end %>


</div>